/**
 * ****************************************
 * @file        Task_nrDemodulate.c
 * @brief       Demodulate
 * @author      yuanfeng
 * @date        2024.5.28
 * @copyright   ACE-Lab(Shanghai University)
 * ****************************************
 */

#include "data_type.h"
#include "riscv_printf.h"
#include "venus.h"
#include "vmath.h"

typedef short __v4096i16 __attribute__((ext_vector_type(4096)));
typedef short __v2048i16 __attribute__((ext_vector_type(2048)));
typedef char  __v4096i8 __attribute__((ext_vector_type(4096)));

// short input_inSignal_real[] = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9};
// short input_inSignal_imag[] = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9};

#define recpSqrt2   0.70710678
#define recpSqrt10  0.316227766016838
#define recpSqrt42  0.154303349962092
#define recpSqrt170 0.076696498884737

// TODO: 暂时将噪声方差定义为short类型，后续需要修改为double类型
// Task_nrEqualize returns sizeof(__v12288i8) for each signal. Keep the
// full transport in distinct input allocations; rxSignalLength still governs
// all demodulation operations and the output sizes are unchanged.
typedef char __v12288i8 __attribute__((ext_vector_type(12288)));
int Task_nrDemodulate(__v12288i8 transport_real, __v12288i8 transport_imag, short_struct input_nModulationSymb,
                      short_struct input_nVar, short_struct input_rxSignalLength) {
  short        nModulationSymb = input_nModulationSymb.data;
  short        nVar            = input_nVar.data;
  short        rxSignalLength  = input_rxSignalLength.data;
  // Extract the algorithm's active prefix into its existing vector types.
  __v4096i8 inSignal_real;
  __v4096i8 inSignal_imag;
  __v2048i16 transport_index;
  vclaim(inSignal_real);
  vclaim(inSignal_imag);
  vclaim(transport_index);
  vrange(transport_index, rxSignalLength);
  vshuffle(inSignal_real, transport_index, transport_real, SHUFFLE_GATHER, rxSignalLength);
  vshuffle(inSignal_imag, transport_index, transport_imag, SHUFFLE_GATHER, rxSignalLength);
  int          fractionLength  = 0;
  short_struct demod_length;
  demod_length.data = rxSignalLength * nModulationSymb;

  // /*--------------------input Signal--------------------*/
  // __v4096i16 inSignal_real;
  // __v4096i16 inSignal_imag;
  // vclaim(inSignal_real);
  // vbarrier();
  // VSPM_OPEN();
  // int inSignal_real_addr = vaddr(inSignal_real);
  // for (int i = 0; i < rxSignalLength; ++i) {
  //   *(volatile short *)(inSignal_real_addr + (i << 1)) =
  //   input_inSignal_real[i];
  // }
  // VSPM_CLOSE();
  // vclaim(inSignal_imag);
  // vbarrier();
  // VSPM_OPEN();
  // int inSignal_imag_addr = vaddr(inSignal_imag);
  // for (int i = 0; i < rxSignalLength; ++i) {
  //   *(volatile short *)(inSignal_imag_addr + (i << 1)) =
  //   input_inSignal_imag[i];
  // }
  // VSPM_CLOSE();

  __v4096i8 softbit;
  vclaim(softbit);
  switch (nModulationSymb) {
  case 2: {
    /*--------------------QPSK Demodulate--------------------*/
    short     d = recpSqrt2 * (1 << fractionLength);
    __v4096i8 softbit1;
    __v4096i8 softbit2;
    // short     factor = d * nVar;
    short factor = 1;
    // short     factor = 4 * d * nVar;
    // vsetshamt(fractionLength);
    softbit1 = vmul(inSignal_real, factor, MASKREAD_OFF, rxSignalLength);
    softbit2 = vmul(inSignal_imag, factor, MASKREAD_OFF, rxSignalLength);
    // vsetshamt(0);
    __v2048i16 softbit_shuffle_index_tmp;
    vclaim(softbit_shuffle_index_tmp);
    vrange(softbit_shuffle_index_tmp, rxSignalLength);
    softbit_shuffle_index_tmp = vmul(softbit_shuffle_index_tmp, 2, MASKREAD_OFF, rxSignalLength);
    vshuffle(softbit, softbit_shuffle_index_tmp, softbit1, SHUFFLE_SCATTER, rxSignalLength);
    softbit_shuffle_index_tmp = vadd(softbit_shuffle_index_tmp, 1, MASKREAD_OFF, rxSignalLength);
    vshuffle(softbit, softbit_shuffle_index_tmp, softbit2, SHUFFLE_SCATTER, rxSignalLength);
  } break;

  case 4: {
    /*--------------------16QAM Demodulate--------------------*/
    short     d = recpSqrt10 * (1 << fractionLength);
    __v4096i8 softbit1;
    __v4096i8 softbit2;
    __v4096i8 softbit3;
    __v4096i8 softbit4;

    /* softbit1 */
    short     factor = 4 * d * nVar;
    __v4096i8 const_value;
    vclaim(const_value);
    vbrdcst(const_value, 2 * d, MASKREAD_OFF, rxSignalLength);
    // vsge(inSignal_real, 2 * d, MASKREAD_OFF, MASKWRITE_ON, rxSignalLength);
    vsle(const_value, inSignal_real, MASKREAD_OFF, MASKWRITE_ON, rxSignalLength);
    vsle(inSignal_real, -2 * d, MASKREAD_ON, MASKWRITE_ON, rxSignalLength);
    vsetshamt(fractionLength);
    softbit1 = vmul(inSignal_real, factor, MASKREAD_ON, rxSignalLength);
    vsetshamt(0);
    vslt(inSignal_real, 2 * d, MASKREAD_OFF, MASKWRITE_ON, rxSignalLength);
    vsetshamt(fractionLength);
    softbit1 = vadd(inSignal_real, -d, MASKREAD_ON, rxSignalLength);
    softbit1 = vmul(inSignal_real, 2 * factor, MASKREAD_ON, rxSignalLength);
    vsetshamt(0);
    vsgt(inSignal_real, -2 * d, MASKREAD_OFF, MASKWRITE_ON, rxSignalLength);
    vsetshamt(fractionLength);
    softbit1 = vadd(inSignal_real, d, MASKREAD_ON, rxSignalLength);
    softbit1 = vmul(inSignal_real, 2 * factor, MASKREAD_ON, rxSignalLength);
    vsetshamt(0);

    /* softbit2 */
    factor = -4 * d * nVar;
    vbrdcst(const_value, 2 * d, MASKREAD_OFF, rxSignalLength);
    // vsge(inSignal_imag, 2 * d, MASKREAD_OFF, MASKWRITE_ON, rxSignalLength);
    vsle(const_value, inSignal_imag, MASKREAD_OFF, MASKWRITE_ON, rxSignalLength);
    vsle(inSignal_imag, -2 * d, MASKREAD_ON, MASKWRITE_ON, rxSignalLength);
    vsetshamt(fractionLength);
    softbit2 = vmul(inSignal_imag, factor, MASKREAD_ON, rxSignalLength);
    vsetshamt(0);
    vslt(inSignal_imag, 2 * d, MASKREAD_OFF, MASKWRITE_ON, rxSignalLength);
    vsetshamt(fractionLength);
    softbit2 = vadd(inSignal_imag, -d, MASKREAD_ON, rxSignalLength);
    softbit2 = vmul(softbit2, 2 * factor, MASKREAD_ON, rxSignalLength);
    vsetshamt(0);
    vsgt(inSignal_imag, -2 * d, MASKREAD_OFF, MASKWRITE_ON, rxSignalLength);
    vsetshamt(fractionLength);
    softbit2 = vadd(inSignal_imag, d, MASKREAD_ON, rxSignalLength);
    softbit2 = vmul(softbit2, 2 * factor, MASKREAD_ON, rxSignalLength);
    vsetshamt(0);

    /* softbit3 */
    vsgt(inSignal_real, 0, MASKREAD_OFF, MASKWRITE_ON, rxSignalLength);
    softbit3 = vxor(inSignal_real, 0xFFFF, MASKREAD_ON, rxSignalLength);
    softbit3 = vsadd(softbit3, 1, MASKREAD_ON, rxSignalLength);
    softbit3 = vadd(softbit3, -2 * d, MASKREAD_ON, rxSignalLength);
    vsetshamt(fractionLength);
    softbit3 = vmul(softbit3, factor, MASKREAD_ON, rxSignalLength);
    vsetshamt(0);

    /* softbit4 */
    vsgt(inSignal_imag, 0, MASKREAD_OFF, MASKWRITE_ON, rxSignalLength);
    softbit4 = vxor(inSignal_imag, 0xFFFF, MASKREAD_ON, rxSignalLength);
    softbit4 = vsadd(softbit4, 1, MASKREAD_ON, rxSignalLength);
    softbit4 = vadd(softbit4, -2 * d, MASKREAD_ON, rxSignalLength);
    vsetshamt(fractionLength);
    softbit4 = vmul(softbit4, factor, MASKREAD_ON, rxSignalLength);
    vsetshamt(0);

    /* data merge */
    __v2048i16 softbit_shuffle_index_tmp;
    vclaim(softbit_shuffle_index_tmp);
    vrange(softbit_shuffle_index_tmp, rxSignalLength);
    softbit_shuffle_index_tmp = vmul(softbit_shuffle_index_tmp, 4, MASKREAD_OFF, rxSignalLength);
    vshuffle(softbit, softbit_shuffle_index_tmp, softbit1, SHUFFLE_SCATTER, rxSignalLength);
    softbit_shuffle_index_tmp = vadd(softbit_shuffle_index_tmp, 1, MASKREAD_OFF, rxSignalLength);
    vshuffle(softbit, softbit_shuffle_index_tmp, softbit2, SHUFFLE_SCATTER, rxSignalLength);
    softbit_shuffle_index_tmp = vadd(softbit_shuffle_index_tmp, 1, MASKREAD_OFF, rxSignalLength);
    vshuffle(softbit, softbit_shuffle_index_tmp, softbit3, SHUFFLE_SCATTER, rxSignalLength);
    softbit_shuffle_index_tmp = vadd(softbit_shuffle_index_tmp, 1, MASKREAD_OFF, rxSignalLength);
    vshuffle(softbit, softbit_shuffle_index_tmp, softbit4, SHUFFLE_SCATTER, rxSignalLength);
  } break;

  case 6: {
    /*--------------------64QAM Demodulate--------------------*/
    short     d = recpSqrt42 * (1 << fractionLength);
    __v4096i8 softbit1;
    __v4096i8 softbit2;
    __v4096i8 softbit3;
    __v4096i8 softbit4;
    __v4096i8 softbit5;
    __v4096i8 softbit6;
    /* softbit1 */
    short factor = 4 * d * nVar;
    vsle(inSignal_real, 6 * d, MASKREAD_OFF, MASKWRITE_ON, rxSignalLength);
    vsetshamt(fractionLength);
    softbit1 = vadd(inSignal_real, -3 * d, MASKREAD_ON, rxSignalLength);
    softbit1 = vmul(softbit1, 4 * factor, MASKREAD_ON, rxSignalLength);
    vsetshamt(0);
    vsgt(inSignal_real, 6 * d, MASKREAD_OFF, MASKWRITE_ON, rxSignalLength);
    vsle(inSignal_real, 4 * d, MASKREAD_ON, MASKWRITE_ON, rxSignalLength);
    vsetshamt(fractionLength);
    softbit1 = vadd(inSignal_real, -2 * d, MASKREAD_ON, rxSignalLength);
    softbit1 = vmul(softbit1, 3 * factor, MASKREAD_ON, rxSignalLength);
    vsetshamt(0);
    vsgt(inSignal_real, 4 * d, MASKREAD_OFF, MASKWRITE_ON, rxSignalLength);
    vsle(inSignal_real, 2 * d, MASKREAD_ON, MASKWRITE_ON, rxSignalLength);
    vsetshamt(fractionLength);
    softbit1 = vadd(inSignal_real, -d, MASKREAD_ON, rxSignalLength);
    softbit1 = vmul(softbit1, 2 * factor, MASKREAD_ON, rxSignalLength);
    vsetshamt(0);
    vsgt(inSignal_real, 2 * d, MASKREAD_OFF, MASKWRITE_ON, rxSignalLength);
    vsle(inSignal_real, -2 * d, MASKREAD_ON, MASKWRITE_ON, rxSignalLength);
    vsetshamt(fractionLength);
    softbit1 = vmul(inSignal_real, factor, MASKREAD_ON, rxSignalLength);
    vsetshamt(0);
    vsgt(inSignal_real, -2 * d, MASKREAD_OFF, MASKWRITE_ON, rxSignalLength);
    vsle(inSignal_real, -4 * d, MASKREAD_ON, MASKWRITE_ON, rxSignalLength);
    vsetshamt(fractionLength);
    softbit1 = vadd(inSignal_real, d, MASKREAD_ON, rxSignalLength);
    softbit1 = vmul(softbit1, 2 * factor, MASKREAD_ON, rxSignalLength);
    vsetshamt(0);
    vsgt(inSignal_real, -4 * d, MASKREAD_OFF, MASKWRITE_ON, rxSignalLength);
    vsle(inSignal_real, -6 * d, MASKREAD_ON, MASKWRITE_ON, rxSignalLength);
    vsetshamt(fractionLength);
    softbit1 = vadd(inSignal_real, 2 * d, MASKREAD_ON, rxSignalLength);
    softbit1 = vmul(softbit1, 3 * factor, MASKREAD_ON, rxSignalLength);
    vsetshamt(0);
    vsgt(inSignal_real, -6 * d, MASKREAD_OFF, MASKWRITE_ON, rxSignalLength);
    vsetshamt(fractionLength);
    softbit1 = vadd(inSignal_real, 3 * d, MASKREAD_ON, rxSignalLength);
    softbit1 = vmul(softbit1, 4 * factor, MASKREAD_ON, rxSignalLength);
    vsetshamt(0);

    /* softbit2 */
    factor = -4 * d * nVar;
    vsle(inSignal_imag, 6 * d, MASKREAD_OFF, MASKWRITE_ON, rxSignalLength);
    vsetshamt(fractionLength);
    softbit2 = vadd(inSignal_imag, -3 * d, MASKREAD_ON, rxSignalLength);
    softbit2 = vmul(softbit2, 4 * factor, MASKREAD_ON, rxSignalLength);
    vsetshamt(0);
    vsgt(inSignal_imag, 6 * d, MASKREAD_OFF, MASKWRITE_ON, rxSignalLength);
    vsle(inSignal_imag, 4 * d, MASKREAD_ON, MASKWRITE_ON, rxSignalLength);
    vsetshamt(fractionLength);
    softbit2 = vadd(inSignal_imag, -2 * d, MASKREAD_ON, rxSignalLength);
    softbit2 = vmul(softbit2, 3 * factor, MASKREAD_ON, rxSignalLength);
    vsetshamt(0);
    vsgt(inSignal_imag, 4 * d, MASKREAD_OFF, MASKWRITE_ON, rxSignalLength);
    vsle(inSignal_imag, 2 * d, MASKREAD_ON, MASKWRITE_ON, rxSignalLength);
    vsetshamt(fractionLength);
    softbit2 = vadd(inSignal_imag, -d, MASKREAD_ON, rxSignalLength);
    softbit2 = vmul(softbit2, 2 * factor, MASKREAD_ON, rxSignalLength);
    vsetshamt(0);
    vsgt(inSignal_imag, 2 * d, MASKREAD_OFF, MASKWRITE_ON, rxSignalLength);
    vsle(inSignal_imag, -2 * d, MASKREAD_ON, MASKWRITE_ON, rxSignalLength);
    vsetshamt(fractionLength);
    softbit2 = vmul(inSignal_imag, factor, MASKREAD_ON, rxSignalLength);
    vsetshamt(0);
    vsgt(inSignal_imag, -2 * d, MASKREAD_OFF, MASKWRITE_ON, rxSignalLength);
    vsle(inSignal_imag, -4 * d, MASKREAD_ON, MASKWRITE_ON, rxSignalLength);
    vsetshamt(fractionLength);
    softbit2 = vadd(inSignal_imag, d, MASKREAD_ON, rxSignalLength);
    softbit2 = vmul(softbit2, 2 * factor, MASKREAD_ON, rxSignalLength);
    vsetshamt(0);
    vsgt(inSignal_imag, -4 * d, MASKREAD_OFF, MASKWRITE_ON, rxSignalLength);
    vsle(inSignal_imag, -6 * d, MASKREAD_ON, MASKWRITE_ON, rxSignalLength);
    vsetshamt(fractionLength);
    softbit2 = vadd(inSignal_imag, 2 * d, MASKREAD_ON, rxSignalLength);
    softbit2 = vmul(softbit2, 3 * factor, MASKREAD_ON, rxSignalLength);
    vsetshamt(0);
    vsgt(inSignal_imag, -6 * d, MASKREAD_OFF, MASKWRITE_ON, rxSignalLength);
    vsetshamt(fractionLength);
    softbit2 = vadd(inSignal_imag, 3 * d, MASKREAD_ON, rxSignalLength);
    softbit2 = vmul(softbit2, 4 * factor, MASKREAD_ON, rxSignalLength);
    vsetshamt(0);

    /* softbit3 */
    factor = 4 * d * nVar;
    vsle(inSignal_real, 6 * d, MASKREAD_OFF, MASKWRITE_ON, rxSignalLength);
    vsetshamt(fractionLength);
    softbit3 = vadd(inSignal_real, -5 * d, MASKREAD_ON, rxSignalLength);
    softbit3 = vmul(softbit3, -2 * factor, MASKREAD_ON, rxSignalLength);
    vsetshamt(0);
    vsgt(inSignal_real, 6 * d, MASKREAD_OFF, MASKWRITE_ON, rxSignalLength);
    vsle(inSignal_real, 2 * d, MASKREAD_ON, MASKWRITE_ON, rxSignalLength);
    vsetshamt(fractionLength);
    softbit3 = vadd(inSignal_real, -4 * d, MASKREAD_ON, rxSignalLength);
    softbit3 = vmul(softbit3, -factor, MASKREAD_ON, rxSignalLength);
    vsetshamt(0);
    vsgt(inSignal_real, 2 * d, MASKREAD_OFF, MASKWRITE_ON, rxSignalLength);
    vsle(inSignal_real, 0, MASKREAD_ON, MASKWRITE_ON, rxSignalLength);
    vsetshamt(fractionLength);
    softbit3 = vadd(inSignal_real, -3 * d, MASKREAD_ON, rxSignalLength);
    softbit3 = vmul(softbit3, -2 * factor, MASKREAD_ON, rxSignalLength);
    vsetshamt(0);
    vsgt(inSignal_real, 0, MASKREAD_OFF, MASKWRITE_ON, rxSignalLength);
    vsle(inSignal_real, -2 * d, MASKREAD_ON, MASKWRITE_ON, rxSignalLength);
    vsetshamt(fractionLength);
    softbit3 = vadd(inSignal_real, 3 * d, MASKREAD_ON, rxSignalLength);
    softbit3 = vmul(softbit3, 2 * factor, MASKREAD_ON, rxSignalLength);
    vsetshamt(0);
    vsgt(inSignal_real, -2 * d, MASKREAD_OFF, MASKWRITE_ON, rxSignalLength);
    vsle(inSignal_real, -6 * d, MASKREAD_ON, MASKWRITE_ON, rxSignalLength);
    vsetshamt(fractionLength);
    softbit3 = vadd(inSignal_real, 4 * d, MASKREAD_ON, rxSignalLength);
    softbit3 = vmul(softbit3, factor, MASKREAD_ON, rxSignalLength);
    vsetshamt(0);
    vsgt(inSignal_real, -6 * d, MASKREAD_OFF, MASKWRITE_ON, rxSignalLength);
    vsetshamt(fractionLength);
    softbit3 = vadd(inSignal_real, 5 * d, MASKREAD_ON, rxSignalLength);
    softbit3 = vmul(softbit3, 2 * factor, MASKREAD_ON, rxSignalLength);
    vsetshamt(0);

    /* softbit4 */
    factor = 4 * d * nVar;
    vsle(inSignal_imag, 6 * d, MASKREAD_OFF, MASKWRITE_ON, rxSignalLength);
    vsetshamt(fractionLength);
    softbit4 = vadd(inSignal_imag, -5 * d, MASKREAD_ON, rxSignalLength);
    softbit4 = vmul(softbit4, -2 * factor, MASKREAD_ON, rxSignalLength);
    vsetshamt(0);
    vsgt(inSignal_imag, 6 * d, MASKREAD_OFF, MASKWRITE_ON, rxSignalLength);
    vsle(inSignal_imag, 2 * d, MASKREAD_ON, MASKWRITE_ON, rxSignalLength);
    vsetshamt(fractionLength);
    softbit4 = vadd(inSignal_imag, -4 * d, MASKREAD_ON, rxSignalLength);
    softbit4 = vmul(softbit4, -factor, MASKREAD_ON, rxSignalLength);
    vsetshamt(0);
    vsgt(inSignal_imag, 2 * d, MASKREAD_OFF, MASKWRITE_ON, rxSignalLength);
    vsle(inSignal_imag, 0, MASKREAD_ON, MASKWRITE_ON, rxSignalLength);
    vsetshamt(fractionLength);
    softbit4 = vadd(inSignal_imag, -3 * d, MASKREAD_ON, rxSignalLength);
    softbit4 = vmul(softbit4, -2 * factor, MASKREAD_ON, rxSignalLength);
    vsetshamt(0);
    vsgt(inSignal_imag, 0, MASKREAD_OFF, MASKWRITE_ON, rxSignalLength);
    vsle(inSignal_imag, -2 * d, MASKREAD_ON, MASKWRITE_ON, rxSignalLength);
    vsetshamt(fractionLength);
    softbit4 = vadd(inSignal_imag, 3 * d, MASKREAD_ON, rxSignalLength);
    softbit4 = vmul(softbit4, 2 * factor, MASKREAD_ON, rxSignalLength);
    vsetshamt(0);
    vsgt(inSignal_imag, -2 * d, MASKREAD_OFF, MASKWRITE_ON, rxSignalLength);
    vsle(inSignal_imag, -6 * d, MASKREAD_ON, MASKWRITE_ON, rxSignalLength);
    vsetshamt(fractionLength);
    softbit4 = vadd(inSignal_imag, 4 * d, MASKREAD_ON, rxSignalLength);
    softbit4 = vmul(softbit4, factor, MASKREAD_ON, rxSignalLength);
    vsetshamt(0);
    vsgt(inSignal_imag, -6 * d, MASKREAD_OFF, MASKWRITE_ON, rxSignalLength);
    vsetshamt(fractionLength);
    softbit4 = vadd(inSignal_imag, 5 * d, MASKREAD_ON, rxSignalLength);
    softbit4 = vmul(softbit4, 2 * factor, MASKREAD_ON, rxSignalLength);
    vsetshamt(0);

    /* softbit5 */
    factor = 4 * d * nVar;
    vsle(inSignal_real, 4 * d, MASKREAD_OFF, MASKWRITE_ON, rxSignalLength);
    vsetshamt(fractionLength);
    softbit5 = vadd(inSignal_real, -6 * d, MASKREAD_ON, rxSignalLength);
    softbit5 = vmul(softbit5, -factor, MASKREAD_ON, rxSignalLength);
    vsetshamt(0);
    vsgt(inSignal_real, 4 * d, MASKREAD_OFF, MASKWRITE_ON, rxSignalLength);
    vsle(inSignal_real, 0, MASKREAD_ON, MASKWRITE_ON, rxSignalLength);
    vsetshamt(fractionLength);
    softbit5 = vadd(inSignal_real, -2 * d, MASKREAD_ON, rxSignalLength);
    softbit5 = vmul(softbit5, factor, MASKREAD_ON, rxSignalLength);
    vsetshamt(0);
    vsgt(inSignal_real, 0, MASKREAD_OFF, MASKWRITE_ON, rxSignalLength);
    vsle(inSignal_real, -4 * d, MASKREAD_ON, MASKWRITE_ON, rxSignalLength);
    vsetshamt(fractionLength);
    softbit5 = vadd(inSignal_real, 2 * d, MASKREAD_ON, rxSignalLength);
    softbit5 = vmul(softbit5, -factor, MASKREAD_ON, rxSignalLength);
    vsetshamt(0);
    vsgt(inSignal_real, -4 * d, MASKREAD_OFF, MASKWRITE_ON, rxSignalLength);
    vsetshamt(fractionLength);
    softbit5 = vadd(inSignal_real, 6 * d, MASKREAD_ON, rxSignalLength);
    softbit5 = vmul(softbit5, factor, MASKREAD_ON, rxSignalLength);
    vsetshamt(0);

    /* softbit6 */
    factor = 4 * d * nVar;
    vsle(inSignal_imag, 4 * d, MASKREAD_OFF, MASKWRITE_ON, rxSignalLength);
    vsetshamt(fractionLength);
    softbit6 = vadd(inSignal_imag, -6 * d, MASKREAD_ON, rxSignalLength);
    softbit6 = vmul(softbit6, -factor, MASKREAD_ON, rxSignalLength);
    vsetshamt(0);
    vsgt(inSignal_imag, 4 * d, MASKREAD_OFF, MASKWRITE_ON, rxSignalLength);
    vsle(inSignal_imag, 0, MASKREAD_ON, MASKWRITE_ON, rxSignalLength);
    vsetshamt(fractionLength);
    softbit6 = vadd(inSignal_imag, -2 * d, MASKREAD_ON, rxSignalLength);
    softbit6 = vmul(softbit6, factor, MASKREAD_ON, rxSignalLength);
    vsetshamt(0);
    vsgt(inSignal_imag, 0, MASKREAD_OFF, MASKWRITE_ON, rxSignalLength);
    vsle(inSignal_imag, -4 * d, MASKREAD_ON, MASKWRITE_ON, rxSignalLength);
    vsetshamt(fractionLength);
    softbit6 = vadd(inSignal_imag, 2 * d, MASKREAD_ON, rxSignalLength);
    softbit6 = vmul(softbit6, -factor, MASKREAD_ON, rxSignalLength);
    vsetshamt(0);
    vsgt(inSignal_imag, -4 * d, MASKREAD_OFF, MASKWRITE_ON, rxSignalLength);
    vsetshamt(fractionLength);
    softbit6 = vadd(inSignal_imag, 6 * d, MASKREAD_ON, rxSignalLength);
    softbit6 = vmul(softbit6, factor, MASKREAD_ON, rxSignalLength);
    vsetshamt(0);

    /* data merge */
    __v2048i16 softbit_shuffle_index_tmp;
    vclaim(softbit_shuffle_index_tmp);
    vrange(softbit_shuffle_index_tmp, rxSignalLength);
    softbit_shuffle_index_tmp = vmul(softbit_shuffle_index_tmp, 6, MASKREAD_OFF, rxSignalLength);
    vshuffle(softbit, softbit_shuffle_index_tmp, softbit1, SHUFFLE_SCATTER, rxSignalLength);
    softbit_shuffle_index_tmp = vadd(softbit_shuffle_index_tmp, 1, MASKREAD_OFF, rxSignalLength);
    vshuffle(softbit, softbit_shuffle_index_tmp, softbit2, SHUFFLE_SCATTER, rxSignalLength);
    softbit_shuffle_index_tmp = vadd(softbit_shuffle_index_tmp, 1, MASKREAD_OFF, rxSignalLength);
    vshuffle(softbit, softbit_shuffle_index_tmp, softbit3, SHUFFLE_SCATTER, rxSignalLength);
    softbit_shuffle_index_tmp = vadd(softbit_shuffle_index_tmp, 1, MASKREAD_OFF, rxSignalLength);
    vshuffle(softbit, softbit_shuffle_index_tmp, softbit4, SHUFFLE_SCATTER, rxSignalLength);
    softbit_shuffle_index_tmp = vadd(softbit_shuffle_index_tmp, 1, MASKREAD_OFF, rxSignalLength);
    vshuffle(softbit, softbit_shuffle_index_tmp, softbit5, SHUFFLE_SCATTER, rxSignalLength);
    softbit_shuffle_index_tmp = vadd(softbit_shuffle_index_tmp, 1, MASKREAD_OFF, rxSignalLength);
    vshuffle(softbit, softbit_shuffle_index_tmp, softbit6, SHUFFLE_SCATTER, rxSignalLength);
  } break;
  case 8: {
    /*--------------------256QAM Demodulate--------------------*/
    short     d = recpSqrt170 * (1 << fractionLength);
    __v4096i8 softbit1;
    __v4096i8 softbit2;
    __v4096i8 softbit3;
    __v4096i8 softbit4;
    __v4096i8 softbit5;
    __v4096i8 softbit6;
    __v4096i8 softbit7;
    __v4096i8 softbit8;
    /* softbit1 */
    short factor = 4 * d * nVar;
    vsle(inSignal_real, 14 * d, MASKREAD_OFF, MASKWRITE_ON, rxSignalLength);
    vsetshamt(fractionLength);
    softbit1 = vadd(inSignal_real, -7 * d, MASKREAD_ON, rxSignalLength);
    softbit1 = vmul(softbit1, 8 * factor, MASKREAD_ON, rxSignalLength);
    vsetshamt(0);
    vsgt(inSignal_real, 14 * d, MASKREAD_OFF, MASKWRITE_ON, rxSignalLength);
    vsle(inSignal_real, 12 * d, MASKREAD_ON, MASKWRITE_ON, rxSignalLength);
    vsetshamt(fractionLength);
    softbit1 = vadd(inSignal_real, -6 * d, MASKREAD_ON, rxSignalLength);
    softbit1 = vmul(softbit1, 7 * factor, MASKREAD_ON, rxSignalLength);
    vsetshamt(0);
    vsgt(inSignal_real, 12 * d, MASKREAD_OFF, MASKWRITE_ON, rxSignalLength);
    vsle(inSignal_real, 10 * d, MASKREAD_ON, MASKWRITE_ON, rxSignalLength);
    vsetshamt(fractionLength);
    softbit1 = vadd(inSignal_real, -5 * d, MASKREAD_ON, rxSignalLength);
    softbit1 = vmul(softbit1, 6 * factor, MASKREAD_ON, rxSignalLength);
    vsetshamt(0);
    vsgt(inSignal_real, 10 * d, MASKREAD_OFF, MASKWRITE_ON, rxSignalLength);
    vsle(inSignal_real, 8 * d, MASKREAD_ON, MASKWRITE_ON, rxSignalLength);
    vsetshamt(fractionLength);
    softbit1 = vadd(inSignal_real, -4 * d, MASKREAD_ON, rxSignalLength);
    softbit1 = vmul(softbit1, 5 * factor, MASKREAD_ON, rxSignalLength);
    vsetshamt(0);
    vsgt(inSignal_real, 8 * d, MASKREAD_OFF, MASKWRITE_ON, rxSignalLength);
    vsle(inSignal_real, 6 * d, MASKREAD_ON, MASKWRITE_ON, rxSignalLength);
    vsetshamt(fractionLength);
    softbit1 = vadd(inSignal_real, -3 * d, MASKREAD_ON, rxSignalLength);
    softbit1 = vmul(softbit1, 4 * factor, MASKREAD_ON, rxSignalLength);
    vsetshamt(0);
    vsgt(inSignal_real, 6 * d, MASKREAD_OFF, MASKWRITE_ON, rxSignalLength);
    vsle(inSignal_real, 4 * d, MASKREAD_ON, MASKWRITE_ON, rxSignalLength);
    vsetshamt(fractionLength);
    softbit1 = vadd(inSignal_real, -2 * d, MASKREAD_ON, rxSignalLength);
    softbit1 = vmul(softbit1, 3 * factor, MASKREAD_ON, rxSignalLength);
    vsetshamt(0);
    vsgt(inSignal_real, 4 * d, MASKREAD_OFF, MASKWRITE_ON, rxSignalLength);
    vsle(inSignal_real, 2 * d, MASKREAD_ON, MASKWRITE_ON, rxSignalLength);
    vsetshamt(fractionLength);
    softbit1 = vadd(inSignal_real, -d, MASKREAD_ON, rxSignalLength);
    softbit1 = vmul(softbit1, 2 * factor, MASKREAD_ON, rxSignalLength);
    vsetshamt(0);
    vsgt(inSignal_real, 2 * d, MASKREAD_OFF, MASKWRITE_ON, rxSignalLength);
    vsle(inSignal_real, -2 * d, MASKREAD_ON, MASKWRITE_ON, rxSignalLength);
    vsetshamt(fractionLength);
    softbit1 = vmul(softbit1, factor, MASKREAD_ON, rxSignalLength);
    vsetshamt(0);
    vsgt(inSignal_real, -2 * d, MASKREAD_OFF, MASKWRITE_ON, rxSignalLength);
    vsle(inSignal_real, -4 * d, MASKREAD_ON, MASKWRITE_ON, rxSignalLength);
    vsetshamt(fractionLength);
    softbit1 = vadd(inSignal_real, d, MASKREAD_ON, rxSignalLength);
    softbit1 = vmul(softbit1, 2 * factor, MASKREAD_ON, rxSignalLength);
    vsetshamt(0);
    vsgt(inSignal_real, -4 * d, MASKREAD_OFF, MASKWRITE_ON, rxSignalLength);
    vsle(inSignal_real, -6 * d, MASKREAD_ON, MASKWRITE_ON, rxSignalLength);
    vsetshamt(fractionLength);
    softbit1 = vadd(inSignal_real, 2 * d, MASKREAD_ON, rxSignalLength);
    softbit1 = vmul(softbit1, 3 * factor, MASKREAD_ON, rxSignalLength);
    vsetshamt(0);
    vsgt(inSignal_real, -6 * d, MASKREAD_OFF, MASKWRITE_ON, rxSignalLength);
    vsle(inSignal_real, -8 * d, MASKREAD_ON, MASKWRITE_ON, rxSignalLength);
    vsetshamt(fractionLength);
    softbit1 = vadd(inSignal_real, 3 * d, MASKREAD_ON, rxSignalLength);
    softbit1 = vmul(softbit1, 4 * factor, MASKREAD_ON, rxSignalLength);
    vsetshamt(0);
    vsgt(inSignal_real, -8 * d, MASKREAD_OFF, MASKWRITE_ON, rxSignalLength);
    vsle(inSignal_real, -10 * d, MASKREAD_ON, MASKWRITE_ON, rxSignalLength);
    vsetshamt(fractionLength);
    softbit1 = vadd(inSignal_real, 4 * d, MASKREAD_ON, rxSignalLength);
    softbit1 = vmul(softbit1, 5 * factor, MASKREAD_ON, rxSignalLength);
    vsetshamt(0);
    vsgt(inSignal_real, -10 * d, MASKREAD_OFF, MASKWRITE_ON, rxSignalLength);
    vsle(inSignal_real, -12 * d, MASKREAD_ON, MASKWRITE_ON, rxSignalLength);
    vsetshamt(fractionLength);
    softbit1 = vadd(inSignal_real, 5 * d, MASKREAD_ON, rxSignalLength);
    softbit1 = vmul(softbit1, 6 * factor, MASKREAD_ON, rxSignalLength);
    vsetshamt(0);
    vsgt(inSignal_real, -12 * d, MASKREAD_OFF, MASKWRITE_ON, rxSignalLength);
    vsle(inSignal_real, -14 * d, MASKREAD_ON, MASKWRITE_ON, rxSignalLength);
    vsetshamt(fractionLength);
    softbit1 = vadd(inSignal_real, 6 * d, MASKREAD_ON, rxSignalLength);
    softbit1 = vmul(softbit1, 7 * factor, MASKREAD_ON, rxSignalLength);
    vsetshamt(0);
    vsgt(inSignal_real, -14 * d, MASKREAD_OFF, MASKWRITE_ON, rxSignalLength);
    vsetshamt(fractionLength);
    softbit1 = vadd(inSignal_real, 7 * d, MASKREAD_ON, rxSignalLength);
    softbit1 = vmul(softbit1, 8 * factor, MASKREAD_ON, rxSignalLength);
    vsetshamt(0);

    /* softbit2 */
    factor = -4 * d * nVar;
    vsle(inSignal_imag, 14 * d, MASKREAD_OFF, MASKWRITE_ON, rxSignalLength);
    vsetshamt(fractionLength);
    softbit2 = vadd(inSignal_imag, -7 * d, MASKREAD_ON, rxSignalLength);
    softbit2 = vmul(softbit2, 8 * factor, MASKREAD_ON, rxSignalLength);
    vsetshamt(0);
    vsgt(inSignal_imag, 14 * d, MASKREAD_OFF, MASKWRITE_ON, rxSignalLength);
    vsle(inSignal_imag, 12 * d, MASKREAD_ON, MASKWRITE_ON, rxSignalLength);
    vsetshamt(fractionLength);
    softbit2 = vadd(inSignal_imag, -6 * d, MASKREAD_ON, rxSignalLength);
    softbit2 = vmul(softbit2, 7 * factor, MASKREAD_ON, rxSignalLength);
    vsetshamt(0);
    vsgt(inSignal_imag, 12 * d, MASKREAD_OFF, MASKWRITE_ON, rxSignalLength);
    vsle(inSignal_imag, 10 * d, MASKREAD_ON, MASKWRITE_ON, rxSignalLength);
    vsetshamt(fractionLength);
    softbit2 = vadd(inSignal_imag, -5 * d, MASKREAD_ON, rxSignalLength);
    softbit2 = vmul(softbit2, 6 * factor, MASKREAD_ON, rxSignalLength);
    vsetshamt(0);
    vsgt(inSignal_imag, 10 * d, MASKREAD_OFF, MASKWRITE_ON, rxSignalLength);
    vsle(inSignal_imag, 8 * d, MASKREAD_ON, MASKWRITE_ON, rxSignalLength);
    vsetshamt(fractionLength);
    softbit2 = vadd(inSignal_imag, -4 * d, MASKREAD_ON, rxSignalLength);
    softbit2 = vmul(softbit2, 5 * factor, MASKREAD_ON, rxSignalLength);
    vsetshamt(0);
    vsgt(inSignal_imag, 8 * d, MASKREAD_OFF, MASKWRITE_ON, rxSignalLength);
    vsle(inSignal_imag, 6 * d, MASKREAD_ON, MASKWRITE_ON, rxSignalLength);
    vsetshamt(fractionLength);
    softbit2 = vadd(inSignal_imag, -3 * d, MASKREAD_ON, rxSignalLength);
    softbit2 = vmul(softbit2, 4 * factor, MASKREAD_ON, rxSignalLength);
    vsetshamt(0);
    vsgt(inSignal_imag, 6 * d, MASKREAD_OFF, MASKWRITE_ON, rxSignalLength);
    vsle(inSignal_imag, 4 * d, MASKREAD_ON, MASKWRITE_ON, rxSignalLength);
    vsetshamt(fractionLength);
    softbit2 = vadd(inSignal_imag, -2 * d, MASKREAD_ON, rxSignalLength);
    softbit2 = vmul(softbit2, 3 * factor, MASKREAD_ON, rxSignalLength);
    vsetshamt(0);
    vsgt(inSignal_imag, 4 * d, MASKREAD_OFF, MASKWRITE_ON, rxSignalLength);
    vsle(inSignal_imag, 2 * d, MASKREAD_ON, MASKWRITE_ON, rxSignalLength);
    vsetshamt(fractionLength);
    softbit2 = vadd(inSignal_imag, -d, MASKREAD_ON, rxSignalLength);
    softbit2 = vmul(softbit2, 2 * factor, MASKREAD_ON, rxSignalLength);
    vsetshamt(0);
    vsgt(inSignal_imag, 2 * d, MASKREAD_OFF, MASKWRITE_ON, rxSignalLength);
    vsle(inSignal_imag, -2 * d, MASKREAD_ON, MASKWRITE_ON, rxSignalLength);
    vsetshamt(fractionLength);
    softbit2 = vmul(softbit2, factor, MASKREAD_ON, rxSignalLength);
    vsetshamt(0);
    vsgt(inSignal_imag, -2 * d, MASKREAD_OFF, MASKWRITE_ON, rxSignalLength);
    vsle(inSignal_imag, -4 * d, MASKREAD_ON, MASKWRITE_ON, rxSignalLength);
    vsetshamt(fractionLength);
    softbit2 = vadd(inSignal_imag, d, MASKREAD_ON, rxSignalLength);
    softbit2 = vmul(softbit2, 2 * factor, MASKREAD_ON, rxSignalLength);
    vsetshamt(0);
    vsgt(inSignal_imag, -4 * d, MASKREAD_OFF, MASKWRITE_ON, rxSignalLength);
    vsle(inSignal_imag, -6 * d, MASKREAD_ON, MASKWRITE_ON, rxSignalLength);
    vsetshamt(fractionLength);
    softbit2 = vadd(inSignal_imag, 2 * d, MASKREAD_ON, rxSignalLength);
    softbit2 = vmul(softbit2, 3 * factor, MASKREAD_ON, rxSignalLength);
    vsetshamt(0);
    vsgt(inSignal_imag, -6 * d, MASKREAD_OFF, MASKWRITE_ON, rxSignalLength);
    vsle(inSignal_imag, -8 * d, MASKREAD_ON, MASKWRITE_ON, rxSignalLength);
    vsetshamt(fractionLength);
    softbit2 = vadd(inSignal_imag, 3 * d, MASKREAD_ON, rxSignalLength);
    softbit2 = vmul(softbit2, 4 * factor, MASKREAD_ON, rxSignalLength);
    vsetshamt(0);
    vsgt(inSignal_imag, -8 * d, MASKREAD_OFF, MASKWRITE_ON, rxSignalLength);
    vsle(inSignal_imag, -10 * d, MASKREAD_ON, MASKWRITE_ON, rxSignalLength);
    vsetshamt(fractionLength);
    softbit2 = vadd(inSignal_imag, 4 * d, MASKREAD_ON, rxSignalLength);
    softbit2 = vmul(softbit2, 5 * factor, MASKREAD_ON, rxSignalLength);
    vsetshamt(0);
    vsgt(inSignal_imag, -10 * d, MASKREAD_OFF, MASKWRITE_ON, rxSignalLength);
    vsle(inSignal_imag, -12 * d, MASKREAD_ON, MASKWRITE_ON, rxSignalLength);
    vsetshamt(fractionLength);
    softbit2 = vadd(inSignal_imag, 5 * d, MASKREAD_ON, rxSignalLength);
    softbit2 = vmul(softbit2, 6 * factor, MASKREAD_ON, rxSignalLength);
    vsetshamt(0);
    vsgt(inSignal_imag, -12 * d, MASKREAD_OFF, MASKWRITE_ON, rxSignalLength);
    vsle(inSignal_imag, -14 * d, MASKREAD_ON, MASKWRITE_ON, rxSignalLength);
    vsetshamt(fractionLength);
    softbit2 = vadd(inSignal_imag, 6 * d, MASKREAD_ON, rxSignalLength);
    softbit2 = vmul(softbit2, 7 * factor, MASKREAD_ON, rxSignalLength);
    vsetshamt(0);
    vsgt(inSignal_imag, -14 * d, MASKREAD_OFF, MASKWRITE_ON, rxSignalLength);
    vsetshamt(fractionLength);
    softbit2 = vadd(inSignal_imag, 7 * d, MASKREAD_ON, rxSignalLength);
    softbit2 = vmul(softbit2, 8 * factor, MASKREAD_ON, rxSignalLength);
    vsetshamt(0);

    /* softbit3 */
    factor = 4 * d * nVar;
    vsle(inSignal_real, 14 * d, MASKREAD_OFF, MASKWRITE_ON, rxSignalLength);
    vsetshamt(fractionLength);
    softbit3 = vadd(inSignal_real, -11 * d, MASKREAD_ON, rxSignalLength);
    softbit3 = vmul(softbit3, -4 * factor, MASKREAD_ON, rxSignalLength);
    vsetshamt(0);
    vsgt(inSignal_real, 14 * d, MASKREAD_OFF, MASKWRITE_ON, rxSignalLength);
    vsle(inSignal_real, 12 * d, MASKREAD_ON, MASKWRITE_ON, rxSignalLength);
    vsetshamt(fractionLength);
    softbit3 = vadd(inSignal_real, -10 * d, MASKREAD_ON, rxSignalLength);
    softbit3 = vmul(softbit3, -3 * factor, MASKREAD_ON, rxSignalLength);
    vsetshamt(0);
    vsgt(inSignal_real, 12 * d, MASKREAD_OFF, MASKWRITE_ON, rxSignalLength);
    vsle(inSignal_real, 10 * d, MASKREAD_ON, MASKWRITE_ON, rxSignalLength);
    vsetshamt(fractionLength);
    softbit3 = vadd(inSignal_real, -9 * d, MASKREAD_ON, rxSignalLength);
    softbit3 = vmul(softbit3, -2 * factor, MASKREAD_ON, rxSignalLength);
    vsetshamt(0);
    vsgt(inSignal_real, 10 * d, MASKREAD_OFF, MASKWRITE_ON, rxSignalLength);
    vsle(inSignal_real, 6 * d, MASKREAD_ON, MASKWRITE_ON, rxSignalLength);
    vsetshamt(fractionLength);
    softbit3 = vadd(inSignal_real, -8 * d, MASKREAD_ON, rxSignalLength);
    softbit3 = vmul(softbit3, -factor, MASKREAD_ON, rxSignalLength);
    vsetshamt(0);
    vsgt(inSignal_real, 6 * d, MASKREAD_OFF, MASKWRITE_ON, rxSignalLength);
    vsle(inSignal_real, 4 * d, MASKREAD_ON, MASKWRITE_ON, rxSignalLength);
    vsetshamt(fractionLength);
    softbit3 = vadd(inSignal_real, -7 * d, MASKREAD_ON, rxSignalLength);
    softbit3 = vmul(softbit3, -2 * factor, MASKREAD_ON, rxSignalLength);
    vsetshamt(0);
    vsgt(inSignal_real, 4 * d, MASKREAD_OFF, MASKWRITE_ON, rxSignalLength);
    vsle(inSignal_real, 2 * d, MASKREAD_ON, MASKWRITE_ON, rxSignalLength);
    vsetshamt(fractionLength);
    softbit3 = vadd(inSignal_real, -6 * d, MASKREAD_ON, rxSignalLength);
    softbit3 = vmul(softbit3, -3 * factor, MASKREAD_ON, rxSignalLength);
    vsetshamt(0);
    vsgt(inSignal_real, 2 * d, MASKREAD_OFF, MASKWRITE_ON, rxSignalLength);
    vsle(inSignal_real, 0, MASKREAD_ON, MASKWRITE_ON, rxSignalLength);
    vsetshamt(fractionLength);
    softbit3 = vadd(inSignal_real, -5 * d, MASKREAD_ON, rxSignalLength);
    softbit3 = vmul(softbit3, -4 * factor, MASKREAD_ON, rxSignalLength);
    vsetshamt(0);
    vsgt(inSignal_real, 0, MASKREAD_OFF, MASKWRITE_ON, rxSignalLength);
    vsle(inSignal_real, -2 * d, MASKREAD_ON, MASKWRITE_ON, rxSignalLength);
    vsetshamt(fractionLength);
    softbit3 = vadd(inSignal_real, 5 * d, MASKREAD_ON, rxSignalLength);
    softbit3 = vmul(softbit3, 4 * factor, MASKREAD_ON, rxSignalLength);
    vsetshamt(0);
    vsgt(inSignal_real, -2 * d, MASKREAD_OFF, MASKWRITE_ON, rxSignalLength);
    vsle(inSignal_real, -4 * d, MASKREAD_ON, MASKWRITE_ON, rxSignalLength);
    vsetshamt(fractionLength);
    softbit3 = vadd(inSignal_real, 6 * d, MASKREAD_ON, rxSignalLength);
    softbit3 = vmul(softbit3, 3 * factor, MASKREAD_ON, rxSignalLength);
    vsetshamt(0);
    vsgt(inSignal_real, -4 * d, MASKREAD_OFF, MASKWRITE_ON, rxSignalLength);
    vsle(inSignal_real, -6 * d, MASKREAD_ON, MASKWRITE_ON, rxSignalLength);
    vsetshamt(fractionLength);
    softbit3 = vadd(inSignal_real, 7 * d, MASKREAD_ON, rxSignalLength);
    softbit3 = vmul(softbit3, 2 * factor, MASKREAD_ON, rxSignalLength);
    vsetshamt(0);
    vsgt(inSignal_real, -6 * d, MASKREAD_OFF, MASKWRITE_ON, rxSignalLength);
    vsle(inSignal_real, -10 * d, MASKREAD_ON, MASKWRITE_ON, rxSignalLength);
    vsetshamt(fractionLength);
    softbit3 = vadd(inSignal_real, 8 * d, MASKREAD_ON, rxSignalLength);
    softbit3 = vmul(softbit3, factor, MASKREAD_ON, rxSignalLength);
    vsetshamt(0);
    vsgt(inSignal_real, -10 * d, MASKREAD_OFF, MASKWRITE_ON, rxSignalLength);
    vsle(inSignal_real, -12 * d, MASKREAD_ON, MASKWRITE_ON, rxSignalLength);
    vsetshamt(fractionLength);
    softbit3 = vadd(inSignal_real, 9 * d, MASKREAD_ON, rxSignalLength);
    softbit3 = vmul(softbit3, 2 * factor, MASKREAD_ON, rxSignalLength);
    vsetshamt(0);
    vsgt(inSignal_real, -12 * d, MASKREAD_OFF, MASKWRITE_ON, rxSignalLength);
    vsle(inSignal_real, -14 * d, MASKREAD_ON, MASKWRITE_ON, rxSignalLength);
    vsetshamt(fractionLength);
    softbit3 = vadd(inSignal_real, 10 * d, MASKREAD_ON, rxSignalLength);
    softbit3 = vmul(softbit3, 3 * factor, MASKREAD_ON, rxSignalLength);
    vsetshamt(0);
    vsgt(inSignal_real, -14 * d, MASKREAD_OFF, MASKWRITE_ON, rxSignalLength);
    vsetshamt(fractionLength);
    softbit3 = vadd(inSignal_real, 11 * d, MASKREAD_ON, rxSignalLength);
    softbit3 = vmul(softbit3, 4 * factor, MASKREAD_ON, rxSignalLength);
    vsetshamt(0);

    /* softbit4 */
    factor = 4 * d * nVar;
    vsle(inSignal_imag, 14 * d, MASKREAD_OFF, MASKWRITE_ON, rxSignalLength);
    vsetshamt(fractionLength);
    softbit4 = vadd(inSignal_imag, -11 * d, MASKREAD_ON, rxSignalLength);
    softbit4 = vmul(softbit4, -4 * factor, MASKREAD_ON, rxSignalLength);
    vsetshamt(0);
    vsgt(inSignal_imag, 14 * d, MASKREAD_OFF, MASKWRITE_ON, rxSignalLength);
    vsle(inSignal_imag, 12 * d, MASKREAD_ON, MASKWRITE_ON, rxSignalLength);
    vsetshamt(fractionLength);
    softbit4 = vadd(inSignal_imag, -10 * d, MASKREAD_ON, rxSignalLength);
    softbit4 = vmul(softbit4, -3 * factor, MASKREAD_ON, rxSignalLength);
    vsetshamt(0);
    vsgt(inSignal_imag, 12 * d, MASKREAD_OFF, MASKWRITE_ON, rxSignalLength);
    vsle(inSignal_imag, 10 * d, MASKREAD_ON, MASKWRITE_ON, rxSignalLength);
    vsetshamt(fractionLength);
    softbit4 = vadd(inSignal_imag, -9 * d, MASKREAD_ON, rxSignalLength);
    softbit4 = vmul(softbit4, -2 * factor, MASKREAD_ON, rxSignalLength);
    vsetshamt(0);
    vsgt(inSignal_imag, 10 * d, MASKREAD_OFF, MASKWRITE_ON, rxSignalLength);
    vsle(inSignal_imag, 6 * d, MASKREAD_ON, MASKWRITE_ON, rxSignalLength);
    vsetshamt(fractionLength);
    softbit4 = vadd(inSignal_imag, -8 * d, MASKREAD_ON, rxSignalLength);
    softbit4 = vmul(softbit4, -factor, MASKREAD_ON, rxSignalLength);
    vsetshamt(0);
    vsgt(inSignal_imag, 6 * d, MASKREAD_OFF, MASKWRITE_ON, rxSignalLength);
    vsle(inSignal_imag, 4 * d, MASKREAD_ON, MASKWRITE_ON, rxSignalLength);
    vsetshamt(fractionLength);
    softbit4 = vadd(inSignal_imag, -7 * d, MASKREAD_ON, rxSignalLength);
    softbit4 = vmul(softbit4, -2 * factor, MASKREAD_ON, rxSignalLength);
    vsetshamt(0);
    vsgt(inSignal_imag, 4 * d, MASKREAD_OFF, MASKWRITE_ON, rxSignalLength);
    vsle(inSignal_imag, 2 * d, MASKREAD_ON, MASKWRITE_ON, rxSignalLength);
    vsetshamt(fractionLength);
    softbit4 = vadd(inSignal_imag, -6 * d, MASKREAD_ON, rxSignalLength);
    softbit4 = vmul(softbit4, -3 * factor, MASKREAD_ON, rxSignalLength);
    vsetshamt(0);
    vsgt(inSignal_imag, 2 * d, MASKREAD_OFF, MASKWRITE_ON, rxSignalLength);
    vsle(inSignal_imag, 0, MASKREAD_ON, MASKWRITE_ON, rxSignalLength);
    vsetshamt(fractionLength);
    softbit4 = vadd(inSignal_imag, -5 * d, MASKREAD_ON, rxSignalLength);
    softbit4 = vmul(softbit4, -4 * factor, MASKREAD_ON, rxSignalLength);
    vsetshamt(0);
    vsgt(inSignal_imag, 0, MASKREAD_OFF, MASKWRITE_ON, rxSignalLength);
    vsle(inSignal_imag, -2 * d, MASKREAD_ON, MASKWRITE_ON, rxSignalLength);
    vsetshamt(fractionLength);
    softbit4 = vadd(inSignal_imag, 5 * d, MASKREAD_ON, rxSignalLength);
    softbit4 = vmul(softbit4, 4 * factor, MASKREAD_ON, rxSignalLength);
    vsetshamt(0);
    vsgt(inSignal_imag, -2 * d, MASKREAD_OFF, MASKWRITE_ON, rxSignalLength);
    vsle(inSignal_imag, -4 * d, MASKREAD_ON, MASKWRITE_ON, rxSignalLength);
    vsetshamt(fractionLength);
    softbit4 = vadd(inSignal_imag, 6 * d, MASKREAD_ON, rxSignalLength);
    softbit4 = vmul(softbit4, 3 * factor, MASKREAD_ON, rxSignalLength);
    vsetshamt(0);
    vsgt(inSignal_imag, -4 * d, MASKREAD_OFF, MASKWRITE_ON, rxSignalLength);
    vsle(inSignal_imag, -6 * d, MASKREAD_ON, MASKWRITE_ON, rxSignalLength);
    vsetshamt(fractionLength);
    softbit4 = vadd(inSignal_imag, 7 * d, MASKREAD_ON, rxSignalLength);
    softbit4 = vmul(softbit4, 2 * factor, MASKREAD_ON, rxSignalLength);
    vsetshamt(0);
    vsgt(inSignal_imag, -6 * d, MASKREAD_OFF, MASKWRITE_ON, rxSignalLength);
    vsle(inSignal_imag, -10 * d, MASKREAD_ON, MASKWRITE_ON, rxSignalLength);
    vsetshamt(fractionLength);
    softbit4 = vadd(inSignal_imag, 8 * d, MASKREAD_ON, rxSignalLength);
    softbit4 = vmul(softbit4, factor, MASKREAD_ON, rxSignalLength);
    vsetshamt(0);
    vsgt(inSignal_imag, -10 * d, MASKREAD_OFF, MASKWRITE_ON, rxSignalLength);
    vsle(inSignal_imag, -12 * d, MASKREAD_ON, MASKWRITE_ON, rxSignalLength);
    vsetshamt(fractionLength);
    softbit4 = vadd(inSignal_imag, 9 * d, MASKREAD_ON, rxSignalLength);
    softbit4 = vmul(softbit4, 2 * factor, MASKREAD_ON, rxSignalLength);
    vsetshamt(0);
    vsgt(inSignal_imag, -12 * d, MASKREAD_OFF, MASKWRITE_ON, rxSignalLength);
    vsle(inSignal_imag, -14 * d, MASKREAD_ON, MASKWRITE_ON, rxSignalLength);
    vsetshamt(fractionLength);
    softbit4 = vadd(inSignal_imag, 10 * d, MASKREAD_ON, rxSignalLength);
    softbit4 = vmul(softbit4, 3 * factor, MASKREAD_ON, rxSignalLength);
    vsetshamt(0);
    vsgt(inSignal_imag, -14 * d, MASKREAD_OFF, MASKWRITE_ON, rxSignalLength);
    vsetshamt(fractionLength);
    softbit4 = vadd(inSignal_imag, 11 * d, MASKREAD_ON, rxSignalLength);
    softbit4 = vmul(softbit4, 4 * factor, MASKREAD_ON, rxSignalLength);
    vsetshamt(0);

    /* softbit5 */
    factor = 4 * d * nVar;
    vsle(inSignal_real, 14 * d, MASKREAD_OFF, MASKWRITE_ON, rxSignalLength);
    vsetshamt(fractionLength);
    softbit5 = vadd(inSignal_real, -13 * d, MASKREAD_ON, rxSignalLength);
    softbit5 = vmul(softbit5, -2 * factor, MASKREAD_ON, rxSignalLength);
    vsetshamt(0);
    vsgt(inSignal_real, 14 * d, MASKREAD_OFF, MASKWRITE_ON, rxSignalLength);
    vsle(inSignal_real, 10 * d, MASKREAD_ON, MASKWRITE_ON, rxSignalLength);
    vsetshamt(fractionLength);
    softbit5 = vadd(inSignal_real, -12 * d, MASKREAD_ON, rxSignalLength);
    softbit5 = vmul(softbit5, -factor, MASKREAD_ON, rxSignalLength);
    vsetshamt(0);
    vsgt(inSignal_real, 10 * d, MASKREAD_OFF, MASKWRITE_ON, rxSignalLength);
    vsle(inSignal_real, 8 * d, MASKREAD_ON, MASKWRITE_ON, rxSignalLength);
    vsetshamt(fractionLength);
    softbit5 = vadd(inSignal_real, -11 * d, MASKREAD_ON, rxSignalLength);
    softbit5 = vmul(softbit5, -2 * factor, MASKREAD_ON, rxSignalLength);
    vsetshamt(0);
    vsgt(inSignal_real, 8 * d, MASKREAD_OFF, MASKWRITE_ON, rxSignalLength);
    vsle(inSignal_real, 6 * d, MASKREAD_ON, MASKWRITE_ON, rxSignalLength);
    vsetshamt(fractionLength);
    softbit5 = vadd(inSignal_real, -5 * d, MASKREAD_ON, rxSignalLength);
    softbit5 = vmul(softbit5, 2 * factor, MASKREAD_ON, rxSignalLength);
    vsetshamt(0);
    vsgt(inSignal_real, 6 * d, MASKREAD_OFF, MASKWRITE_ON, rxSignalLength);
    vsle(inSignal_real, 2 * d, MASKREAD_ON, MASKWRITE_ON, rxSignalLength);
    vsetshamt(fractionLength);
    softbit5 = vadd(inSignal_real, -4 * d, MASKREAD_ON, rxSignalLength);
    softbit5 = vmul(softbit5, factor, MASKREAD_ON, rxSignalLength);
    vsetshamt(0);
    vsgt(inSignal_real, 2 * d, MASKREAD_OFF, MASKWRITE_ON, rxSignalLength);
    vsle(inSignal_real, 0, MASKREAD_ON, MASKWRITE_ON, rxSignalLength);
    vsetshamt(fractionLength);
    softbit5 = vadd(inSignal_real, -3 * d, MASKREAD_ON, rxSignalLength);
    softbit5 = vmul(softbit5, 2 * factor, MASKREAD_ON, rxSignalLength);
    vsetshamt(0);
    vsgt(inSignal_real, 0, MASKREAD_OFF, MASKWRITE_ON, rxSignalLength);
    vsle(inSignal_real, -2 * d, MASKREAD_ON, MASKWRITE_ON, rxSignalLength);
    vsetshamt(fractionLength);
    softbit5 = vadd(inSignal_real, 3 * d, MASKREAD_ON, rxSignalLength);
    softbit5 = vmul(softbit5, -2 * factor, MASKREAD_ON, rxSignalLength);
    vsetshamt(0);
    vsgt(inSignal_real, -2 * d, MASKREAD_OFF, MASKWRITE_ON, rxSignalLength);
    vsle(inSignal_real, -6 * d, MASKREAD_ON, MASKWRITE_ON, rxSignalLength);
    vsetshamt(fractionLength);
    softbit5 = vadd(inSignal_real, 4 * d, MASKREAD_ON, rxSignalLength);
    softbit5 = vmul(softbit5, -factor, MASKREAD_ON, rxSignalLength);
    vsetshamt(0);
    vsgt(inSignal_real, -6 * d, MASKREAD_OFF, MASKWRITE_ON, rxSignalLength);
    vsle(inSignal_real, -8 * d, MASKREAD_ON, MASKWRITE_ON, rxSignalLength);
    vsetshamt(fractionLength);
    softbit5 = vadd(inSignal_real, 5 * d, MASKREAD_ON, rxSignalLength);
    softbit5 = vmul(softbit5, -2 * factor, MASKREAD_ON, rxSignalLength);
    vsetshamt(0);
    vsgt(inSignal_real, -8 * d, MASKREAD_OFF, MASKWRITE_ON, rxSignalLength);
    vsle(inSignal_real, -10 * d, MASKREAD_ON, MASKWRITE_ON, rxSignalLength);
    vsetshamt(fractionLength);
    softbit5 = vadd(inSignal_real, 11 * d, MASKREAD_ON, rxSignalLength);
    softbit5 = vmul(softbit5, 2 * factor, MASKREAD_ON, rxSignalLength);
    vsetshamt(0);
    vsgt(inSignal_real, -10 * d, MASKREAD_OFF, MASKWRITE_ON, rxSignalLength);
    vsle(inSignal_real, -14 * d, MASKREAD_ON, MASKWRITE_ON, rxSignalLength);
    vsetshamt(fractionLength);
    softbit5 = vadd(inSignal_real, 12 * d, MASKREAD_ON, rxSignalLength);
    softbit5 = vmul(softbit5, factor, MASKREAD_ON, rxSignalLength);
    vsetshamt(0);
    vsgt(inSignal_real, -14 * d, MASKREAD_OFF, MASKWRITE_ON, rxSignalLength);
    vsetshamt(fractionLength);
    softbit5 = vadd(inSignal_real, 13 * d, MASKREAD_ON, rxSignalLength);
    softbit5 = vmul(softbit5, 2 * factor, MASKREAD_ON, rxSignalLength);
    vsetshamt(0);

    /* softbit6 */
    factor = 4 * d * nVar;
    vsle(inSignal_imag, 14 * d, MASKREAD_OFF, MASKWRITE_ON, rxSignalLength);
    vsetshamt(fractionLength);
    softbit6 = vadd(inSignal_imag, -13 * d, MASKREAD_ON, rxSignalLength);
    softbit6 = vmul(softbit6, -2 * factor, MASKREAD_ON, rxSignalLength);
    vsetshamt(0);
    vsgt(inSignal_imag, 14 * d, MASKREAD_OFF, MASKWRITE_ON, rxSignalLength);
    vsle(inSignal_imag, 10 * d, MASKREAD_ON, MASKWRITE_ON, rxSignalLength);
    vsetshamt(fractionLength);
    softbit6 = vadd(inSignal_imag, -12 * d, MASKREAD_ON, rxSignalLength);
    softbit6 = vmul(softbit6, -factor, MASKREAD_ON, rxSignalLength);
    vsetshamt(0);
    vsgt(inSignal_imag, 10 * d, MASKREAD_OFF, MASKWRITE_ON, rxSignalLength);
    vsle(inSignal_imag, 8 * d, MASKREAD_ON, MASKWRITE_ON, rxSignalLength);
    vsetshamt(fractionLength);
    softbit6 = vadd(inSignal_imag, -11 * d, MASKREAD_ON, rxSignalLength);
    softbit6 = vmul(softbit6, -2 * factor, MASKREAD_ON, rxSignalLength);
    vsetshamt(0);
    vsgt(inSignal_imag, 8 * d, MASKREAD_OFF, MASKWRITE_ON, rxSignalLength);
    vsle(inSignal_imag, 6 * d, MASKREAD_ON, MASKWRITE_ON, rxSignalLength);
    vsetshamt(fractionLength);
    softbit6 = vadd(inSignal_imag, -5 * d, MASKREAD_ON, rxSignalLength);
    softbit6 = vmul(softbit6, 2 * factor, MASKREAD_ON, rxSignalLength);
    vsetshamt(0);
    vsgt(inSignal_imag, 6 * d, MASKREAD_OFF, MASKWRITE_ON, rxSignalLength);
    vsle(inSignal_imag, 2 * d, MASKREAD_ON, MASKWRITE_ON, rxSignalLength);
    vsetshamt(fractionLength);
    softbit6 = vadd(inSignal_imag, -4 * d, MASKREAD_ON, rxSignalLength);
    softbit6 = vmul(softbit6, factor, MASKREAD_ON, rxSignalLength);
    vsetshamt(0);
    vsgt(inSignal_imag, 2 * d, MASKREAD_OFF, MASKWRITE_ON, rxSignalLength);
    vsle(inSignal_imag, 0, MASKREAD_ON, MASKWRITE_ON, rxSignalLength);
    vsetshamt(fractionLength);
    softbit6 = vadd(inSignal_imag, -3 * d, MASKREAD_ON, rxSignalLength);
    softbit6 = vmul(softbit6, 2 * factor, MASKREAD_ON, rxSignalLength);
    vsetshamt(0);
    vsgt(inSignal_imag, 0, MASKREAD_OFF, MASKWRITE_ON, rxSignalLength);
    vsle(inSignal_imag, -2 * d, MASKREAD_ON, MASKWRITE_ON, rxSignalLength);
    vsetshamt(fractionLength);
    softbit6 = vadd(inSignal_imag, 3 * d, MASKREAD_ON, rxSignalLength);
    softbit6 = vmul(softbit6, -2 * factor, MASKREAD_ON, rxSignalLength);
    vsetshamt(0);
    vsgt(inSignal_imag, -2 * d, MASKREAD_OFF, MASKWRITE_ON, rxSignalLength);
    vsle(inSignal_imag, -6 * d, MASKREAD_ON, MASKWRITE_ON, rxSignalLength);
    vsetshamt(fractionLength);
    softbit6 = vadd(inSignal_imag, 4 * d, MASKREAD_ON, rxSignalLength);
    softbit6 = vmul(softbit6, -factor, MASKREAD_ON, rxSignalLength);
    vsetshamt(0);
    vsgt(inSignal_imag, -6 * d, MASKREAD_OFF, MASKWRITE_ON, rxSignalLength);
    vsle(inSignal_imag, -8 * d, MASKREAD_ON, MASKWRITE_ON, rxSignalLength);
    vsetshamt(fractionLength);
    softbit6 = vadd(inSignal_imag, 5 * d, MASKREAD_ON, rxSignalLength);
    softbit6 = vmul(softbit6, -2 * factor, MASKREAD_ON, rxSignalLength);
    vsetshamt(0);
    vsgt(inSignal_imag, -8 * d, MASKREAD_OFF, MASKWRITE_ON, rxSignalLength);
    vsle(inSignal_imag, -10 * d, MASKREAD_ON, MASKWRITE_ON, rxSignalLength);
    vsetshamt(fractionLength);
    softbit6 = vadd(inSignal_imag, 11 * d, MASKREAD_ON, rxSignalLength);
    softbit6 = vmul(softbit6, 2 * factor, MASKREAD_ON, rxSignalLength);
    vsetshamt(0);
    vsgt(inSignal_imag, -10 * d, MASKREAD_OFF, MASKWRITE_ON, rxSignalLength);
    vsle(inSignal_imag, -14 * d, MASKREAD_ON, MASKWRITE_ON, rxSignalLength);
    vsetshamt(fractionLength);
    softbit6 = vadd(inSignal_imag, 12 * d, MASKREAD_ON, rxSignalLength);
    softbit6 = vmul(softbit6, factor, MASKREAD_ON, rxSignalLength);
    vsetshamt(0);
    vsgt(inSignal_imag, -14 * d, MASKREAD_OFF, MASKWRITE_ON, rxSignalLength);
    vsetshamt(fractionLength);
    softbit6 = vadd(inSignal_imag, 13 * d, MASKREAD_ON, rxSignalLength);
    softbit6 = vmul(softbit6, 2 * factor, MASKREAD_ON, rxSignalLength);
    vsetshamt(0);

    /* softbit7 */
    factor = 4 * d * nVar;
    vsle(inSignal_real, 12 * d, MASKREAD_OFF, MASKWRITE_ON, rxSignalLength);
    vsetshamt(fractionLength);
    softbit7 = vadd(inSignal_real, -14 * d, MASKREAD_ON, rxSignalLength);
    softbit7 = vmul(softbit7, -factor, MASKREAD_ON, rxSignalLength);
    vsetshamt(0);
    vsgt(inSignal_real, 12 * d, MASKREAD_OFF, MASKWRITE_ON, rxSignalLength);
    vsle(inSignal_real, 8 * d, MASKREAD_ON, MASKWRITE_ON, rxSignalLength);
    vsetshamt(fractionLength);
    softbit7 = vadd(inSignal_real, -10 * d, MASKREAD_ON, rxSignalLength);
    softbit7 = vmul(softbit7, factor, MASKREAD_ON, rxSignalLength);
    vsetshamt(0);
    vsgt(inSignal_real, 8 * d, MASKREAD_OFF, MASKWRITE_ON, rxSignalLength);
    vsle(inSignal_real, 4 * d, MASKREAD_ON, MASKWRITE_ON, rxSignalLength);
    vsetshamt(fractionLength);
    softbit7 = vadd(inSignal_real, -6 * d, MASKREAD_ON, rxSignalLength);
    softbit7 = vmul(softbit7, -factor, MASKREAD_ON, rxSignalLength);
    vsetshamt(0);
    vsgt(inSignal_real, 4 * d, MASKREAD_OFF, MASKWRITE_ON, rxSignalLength);
    vsle(inSignal_real, 0, MASKREAD_ON, MASKWRITE_ON, rxSignalLength);
    vsetshamt(fractionLength);
    softbit7 = vadd(inSignal_real, -2 * d, MASKREAD_ON, rxSignalLength);
    softbit7 = vmul(softbit7, factor, MASKREAD_ON, rxSignalLength);
    vsetshamt(0);
    vsgt(inSignal_real, 0, MASKREAD_OFF, MASKWRITE_ON, rxSignalLength);
    vsle(inSignal_real, -4 * d, MASKREAD_ON, MASKWRITE_ON, rxSignalLength);
    vsetshamt(fractionLength);
    softbit7 = vadd(inSignal_real, 2 * d, MASKREAD_ON, rxSignalLength);
    softbit7 = vmul(softbit7, -factor, MASKREAD_ON, rxSignalLength);
    vsetshamt(0);
    vsgt(inSignal_real, -4 * d, MASKREAD_OFF, MASKWRITE_ON, rxSignalLength);
    vsle(inSignal_real, -8 * d, MASKREAD_ON, MASKWRITE_ON, rxSignalLength);
    vsetshamt(fractionLength);
    softbit7 = vadd(inSignal_real, 6 * d, MASKREAD_ON, rxSignalLength);
    softbit7 = vmul(softbit7, factor, MASKREAD_ON, rxSignalLength);
    vsetshamt(0);
    vsgt(inSignal_real, -8 * d, MASKREAD_OFF, MASKWRITE_ON, rxSignalLength);
    vsle(inSignal_real, -12 * d, MASKREAD_ON, MASKWRITE_ON, rxSignalLength);
    vsetshamt(fractionLength);
    softbit7 = vadd(inSignal_real, 10 * d, MASKREAD_ON, rxSignalLength);
    softbit7 = vmul(softbit7, -factor, MASKREAD_ON, rxSignalLength);
    vsetshamt(0);
    vsgt(inSignal_real, -14 * d, MASKREAD_OFF, MASKWRITE_ON, rxSignalLength);
    vsetshamt(fractionLength);
    softbit7 = vadd(inSignal_real, 14 * d, MASKREAD_ON, rxSignalLength);
    softbit7 = vmul(softbit7, factor, MASKREAD_ON, rxSignalLength);
    vsetshamt(0);

    /* softbit8 */
    factor = 4 * d * nVar;
    vsle(inSignal_imag, 12 * d, MASKREAD_OFF, MASKWRITE_ON, rxSignalLength);
    vsetshamt(fractionLength);
    softbit8 = vadd(inSignal_imag, -14 * d, MASKREAD_ON, rxSignalLength);
    softbit8 = vmul(softbit8, -factor, MASKREAD_ON, rxSignalLength);
    vsetshamt(0);

    vsgt(inSignal_imag, 12 * d, MASKREAD_OFF, MASKWRITE_ON, rxSignalLength);
    vsle(inSignal_imag, 8 * d, MASKREAD_ON, MASKWRITE_ON, rxSignalLength);
    vsetshamt(fractionLength);
    softbit8 = vadd(inSignal_imag, -10 * d, MASKREAD_ON, rxSignalLength);
    softbit8 = vmul(softbit8, factor, MASKREAD_ON, rxSignalLength);
    vsetshamt(0);

    vsgt(inSignal_imag, 8 * d, MASKREAD_OFF, MASKWRITE_ON, rxSignalLength);
    vsle(inSignal_imag, 4 * d, MASKREAD_ON, MASKWRITE_ON, rxSignalLength);
    vsetshamt(fractionLength);
    softbit8 = vadd(inSignal_imag, -6 * d, MASKREAD_ON, rxSignalLength);
    softbit8 = vmul(softbit8, -factor, MASKREAD_ON, rxSignalLength);
    vsetshamt(0);

    vsgt(inSignal_imag, 4 * d, MASKREAD_OFF, MASKWRITE_ON, rxSignalLength);
    vsle(inSignal_imag, 0, MASKREAD_ON, MASKWRITE_ON, rxSignalLength);
    vsetshamt(fractionLength);
    softbit8 = vadd(inSignal_imag, -2 * d, MASKREAD_ON, rxSignalLength);
    softbit8 = vmul(softbit8, factor, MASKREAD_ON, rxSignalLength);
    vsetshamt(0);

    vsgt(inSignal_imag, 0, MASKREAD_OFF, MASKWRITE_ON, rxSignalLength);
    vsle(inSignal_imag, -4 * d, MASKREAD_ON, MASKWRITE_ON, rxSignalLength);
    vsetshamt(fractionLength);
    softbit8 = vadd(inSignal_imag, 2 * d, MASKREAD_ON, rxSignalLength);
    softbit8 = vmul(softbit8, -factor, MASKREAD_ON, rxSignalLength);
    vsetshamt(0);

    vsgt(inSignal_imag, -4 * d, MASKREAD_OFF, MASKWRITE_ON, rxSignalLength);
    vsle(inSignal_imag, -8 * d, MASKREAD_ON, MASKWRITE_ON, rxSignalLength);
    vsetshamt(fractionLength);
    softbit8 = vadd(inSignal_imag, 6 * d, MASKREAD_ON, rxSignalLength);
    softbit8 = vmul(softbit8, factor, MASKREAD_ON, rxSignalLength);
    vsetshamt(0);

    vsgt(inSignal_imag, -8 * d, MASKREAD_OFF, MASKWRITE_ON, rxSignalLength);
    vsle(inSignal_imag, -12 * d, MASKREAD_ON, MASKWRITE_ON, rxSignalLength);
    vsetshamt(fractionLength);
    softbit8 = vadd(inSignal_imag, 10 * d, MASKREAD_ON, rxSignalLength);
    softbit8 = vmul(softbit8, -factor, MASKREAD_ON, rxSignalLength);
    vsetshamt(0);

    vsgt(inSignal_imag, -14 * d, MASKREAD_OFF, MASKWRITE_ON, rxSignalLength);
    vsetshamt(fractionLength);
    softbit8 = vadd(inSignal_imag, 14 * d, MASKREAD_ON, rxSignalLength);
    softbit8 = vmul(softbit8, factor, MASKREAD_ON, rxSignalLength);
    vsetshamt(0);

    /* data merge */
    __v2048i16 softbit_shuffle_index_tmp;
    vclaim(softbit_shuffle_index_tmp);
    vrange(softbit_shuffle_index_tmp, rxSignalLength);
    softbit_shuffle_index_tmp = vmul(softbit_shuffle_index_tmp, 6, MASKREAD_OFF, rxSignalLength);
    vshuffle(softbit, softbit_shuffle_index_tmp, softbit1, SHUFFLE_SCATTER, rxSignalLength);
    softbit_shuffle_index_tmp = vadd(softbit_shuffle_index_tmp, 1, MASKREAD_OFF, rxSignalLength);
    vshuffle(softbit, softbit_shuffle_index_tmp, softbit2, SHUFFLE_SCATTER, rxSignalLength);
    softbit_shuffle_index_tmp = vadd(softbit_shuffle_index_tmp, 1, MASKREAD_OFF, rxSignalLength);
    vshuffle(softbit, softbit_shuffle_index_tmp, softbit3, SHUFFLE_SCATTER, rxSignalLength);
    softbit_shuffle_index_tmp = vadd(softbit_shuffle_index_tmp, 1, MASKREAD_OFF, rxSignalLength);
    vshuffle(softbit, softbit_shuffle_index_tmp, softbit4, SHUFFLE_SCATTER, rxSignalLength);
    softbit_shuffle_index_tmp = vadd(softbit_shuffle_index_tmp, 1, MASKREAD_OFF, rxSignalLength);
    vshuffle(softbit, softbit_shuffle_index_tmp, softbit5, SHUFFLE_SCATTER, rxSignalLength);
    softbit_shuffle_index_tmp = vadd(softbit_shuffle_index_tmp, 1, MASKREAD_OFF, rxSignalLength);
    vshuffle(softbit, softbit_shuffle_index_tmp, softbit6, SHUFFLE_SCATTER, rxSignalLength);
    softbit_shuffle_index_tmp = vadd(softbit_shuffle_index_tmp, 1, MASKREAD_OFF, rxSignalLength);
    vshuffle(softbit, softbit_shuffle_index_tmp, softbit7, SHUFFLE_SCATTER, rxSignalLength);
    softbit_shuffle_index_tmp = vadd(softbit_shuffle_index_tmp, 1, MASKREAD_OFF, rxSignalLength);
    vshuffle(softbit, softbit_shuffle_index_tmp, softbit6, SHUFFLE_SCATTER, rxSignalLength);
  } break;
  default:
    break;
  }

  vreturn(softbit, sizeof(softbit), &demod_length, sizeof(demod_length));
}